---
# yamllint disable rule:line-length
argument_specs:
  main:
    short_description: "Prometheus apache_exporter"
    description:
      - "Deploy prometheus L(apache exporter,https://github.com/Lusitaniae/apache_exporter) using ansible"
    author:
      - "Prometheus Community"
    options:
      apache_exporter_version:
        description: "apache_exporter package version. Also accepts latest as parameter."
        default: "1.0.7"
      apache_exporter_skip_install:
        description: "apache_exporter installation tasks gets skipped when set to true."
        type: bool
        default: false
      apache_exporter_binary_local_dir:
        description:
          - "Enables the use of local packages instead of those distributed on github."
          - "The parameter may be set to a directory where the C(apache_exporter) binary is stored on the host where ansible is run."
          - "This overrides the I(apache_exporter_version) parameter"
      apache_exporter_binary_url:
        description: "URL of the apache_exporter binaries .tar.gz file"
        default: "https://github.com/{{ _apache_exporter_repo }}/releases/download/v{{ apache_exporter_version }}/apache_exporter-{{ apache_exporter_version }}.linux-{{ go_arch }}.tar.gz"
      apache_exporter_checksums_url:
        description: "URL of the apache_exporter checksums file"
        default: "https://github.com/{{ _apache_exporter_repo }}/releases/download/v{{ apache_exporter_version }}/apache_exporter-{{ apache_exporter_version }}_checksums.txt"
      apache_exporter_web_listen_address:
        description: "Address on which apache exporter will listen"
        default: "0.0.0.0:9117"
      apache_exporter_web_telemetry_path:
        description: "Path under which to expose metrics"
        default: "/metrics"
      apache_exporter_tls_server_config:
        description:
          - "Configuration for TLS authentication."
          - "Keys and values are the same as in L(apache_exporter docs,https://github.com/prometheus/exporter-toolkit/blob/master/docs/web-configuration.md)."
        type: "dict"
      apache_exporter_http_server_config:
        description:
          - "Config for HTTP/2 support."
          - "Keys and values are the same as in L(apache_exporter docs,https://github.com/prometheus/exporter-toolkit/blob/master/docs/web-configuration.md)."
        type: "dict"
      apache_exporter_basic_auth_users:
        description: "Dictionary of users and password for basic authentication. Passwords are automatically hashed with bcrypt."
        type: "dict"
      apache_exporter_log_level:
        description: "Only log messages with the given severity or above. One of: [debug, info, warn, error]"
        default: "info"
      apache_exporter_log_format:
        description: "Output format of log messages. One of: [logfmt, json]"
        default: "logfmt"
      apache_exporter_scrape_uri:
        description: "A URI or unix domain socket path for scraping apache metrics.."
        default: "http://127.0.0.1/server-status/?auto"
      apache_exporter_binary_install_dir:
        description:
          - "I(Advanced)"
          - "Directory to install apache_exporter binary"
        default: "/usr/local/bin"
      apache_exporter_system_group:
        description:
          - "I(Advanced)"
          - "System group for apache_exporter"
        default: "apache-exp"
      apache_exporter_system_user:
        description:
          - "I(Advanced)"
          - "apache_exporter user"
        default: "apache-exp"
      apache_exporter_archive_path:
        description: 'Local path to stash the archive and its extraction'
        default: "/tmp"
