---
provisioner:
  inventory:
    group_vars:
      all:
        apache_exporter_binary_local_dir: "/tmp/apache_exporter-1.0.7.linuxamd64_local"
        apache_exporter_web_listen_address: "127.0.0.1:9117"

        apache_exporter_tls_server_config:
          cert_file: /etc/apache_exporter/tls.cert
          key_file: /etc/apache_exporter/tls.key
        apache_exporter_http_server_config:
          http2: true
        apache_exporter_basic_auth_users:
          randomuser: examplepassword
        go_arch: amd64
        apache_exporter_version: 1.0.7
