---
- name: Copy the apache_exporter systemd service file
  ansible.builtin.template:
    src: apache_exporter.service.j2
    dest: /etc/systemd/system/apache_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart apache_exporter

- name: Create apache_exporter config directory
  ansible.builtin.file:
    path: "/etc/apache_exporter"
    state: directory
    owner: root
    group: root
    mode: u+rwX,g+rwX,o=rX

- name: Copy the apache_exporter web config file
  ansible.builtin.template:
    src: web_config.yaml.j2
    dest: /etc/apache_exporter/web_config.yaml
    owner: root
    group: root
    mode: 0644
  notify: restart apache_exporter

- name: Allow apache_exporter port in SELinux on RedHat OS family
  community.general.seport:
    ports: "{{ apache_exporter_web_listen_address.split(':')[-1] }}"
    proto: tcp
    setype: http_port_t
    state: present
  when:
    - ansible_version.full is version_compare('2.4', '>=')
    - ansible_selinux.status == "enabled"
